# Generated by Django 4.2 on 2023-10-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_zapisverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZapisVerification',
        ),
    ]
