# Generated by Django 4.2 on 2023-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='black', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='shredder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
