# Generated by Django 4.2 on 2023-10-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_proba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proba',
        ),
    ]
