# Generated by Django 4.2 on 2023-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shredder',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='water',
            field=models.CharField(max_length=20),
        ),
    ]
