# Generated by Django 4.2 on 2023-11-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='hand',
            field=models.CharField(default='praworecznosc', max_length=50),
        ),
        migrations.AddField(
            model_name='useritem',
            name='size',
            field=models.CharField(default='180x60', max_length=20),
        ),
    ]
