# Generated by Django 4.2 on 2023-11-25 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_useritem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
